os:
  - linux
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  - python -m unittest discover -s tests
