name: Bloom Release

on:
  release:
    types: [created]

jobs:
  bloom-release:
    runs-on: ubuntu-latest
    steps:
      - name: bloom release
        uses: at-wat/bloom-release-action@v0.0.8
        with:
          ros_distro: foxy
          github_token_bloom: ${{ secrets.BLOOM_TOKEN }}
          github_user: DavidMansolino
          git_user: DavidMansolino
          git_email: David.Mansolino@cyberbotics.com
          release_repository_push_url: https://github.com/${{ github.repository }}-release.git
          # open_pr: true
